config/routes.rb
Rails.application.routes.draw do
  
  
  root 'sessions#new'
  get '/club', to: 'clubs#show'
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  
  validates :first_name, presence: true
  validates :last_name, presence: true

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64

  end
  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

    # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :require_login
	protect_from_forgery with: :exception
	include SessionsHelper
private
 
  def require_login
    unless logged_in?
      flash[:danger] = "You must be logged in order to access this section"
      redirect_to login_path
    end
  end

end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  def new
  end

  def show
  	@user = User.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 before_action :user_authenticated, only: [:new]
 skip_before_action :require_login, only: [:new, :create]
  def new
  @user = User.new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    user_last_name = User.find_by(last_name: params[:session][:last_name])
     if (user == nil || user_last_name == nil)
      flash[:danger] = 'Invalid combination'
      render 'new'
    else (user.id == user_last_name.id)
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    end
  end
  def show
    
  end

    def destroy
      log_out
      redirect_to login_path
    end

    def user_authenticated
      if logged_in?
        redirect_to user_path(@current_user)
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_action :require_login, only: [:new, :create]
	def index
		@users = User.all
		
	end
	def new
		@user = User.new
	end

	def show
		@user = User.find(params[:id])
	end

	def create
		@user = User.new(user_params)
		if @user.save
			log_in @user
			flash[:success] = "Welcome #{@user.email}"
			redirect_to @user
		else
			flash[:danger] = "You have to fill up every imput properly"
			redirect_to login_path
		end
	end

  private

    def user_params
      params.require(:user).permit(:first_name, :last_name,:email)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

    # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

    # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

    # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clubs/new.html.erb
<h1>Clubs#new</h1>
<p>Find me in app/views/clubs/new.html.erb</p>

app/views/clubs/show.html.erb
<h1>Te voila dans notre club</h1>


  <% @user.each do |x|%>
    <div class="card form-group" style="width: 18rem;">
    <div class="card-body">
    <h5 class="card-title"><%= x.first_name %></h5>
    <h6 class="card-title"><%= x.last_name %></h6>
    <p class="card-text"><%= x.email %></p>
    </div>
  </div>
  <% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
		<li><%= link_to "Log out", logout_path, class: "btn btn-danger",method: :delete %></li>
   		<li><%= link_to "Viens dans notre club", club_path, class: "btn btn-primary" %></li>
    	<li><%= link_to "accueil", user_path(@current_user), class: "btn btn-primary" %></li>
	</ul>
	</div>
</nav>

app/views/layouts/_loginheader.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= form_for(:session, url: login_path, :html => {:class => 'form-inline my-2 my-lg-0'}) do |f| %>
      <%= f.email_field :email, class: 'form-control mr-sm-2', placeholder:'Email'  %>
      <%= f.text_field :last_name, class: 'form-control mr-sm-2', placeholder:'Last name' %>
      <%= f.submit "Log in", class: "btn btn-outline-success my-2 my-sm-0" %>
       <%= f.label :remember_me, class: "checkbox inline", id: "checkbox" do %>
       <%= f.check_box :remember_me %>
        <span> Remember me </span>
      <% end %>
     <% end %>
    </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>Testapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if content_for?(:navbar) %>
    <%= yield(:navbar) %>
<% else %>
   <%= render 'layouts/header' %>
<% end %>
<div class="flash">
  <div class="flash">
  <% if flash[:danger] %>
    <div class="alert alert-danger"><%= flash[:danger] %></div>
  <% end %>
  <% if flash[:success] %>
    <div class="alert alert-danger"><%= flash[:success] %></div>
  <% end %>
</div>
    <%= yield %>
  </body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</html>

app/views/users/new.html.erb
<%= current_user.email %>

app/views/users/show.html.erb
</br></br></br></br>
<h1 class= "new">Hello <%= @user.first_name%></h1>